### ISSUE TITLE
Do not show panel if closed 

### ISSUE THREAD

**Issue by phatmann** [jscheffner/vscode-workspace-terminals#3]
When automatic terminal switching is turned on, the Panel pane is opened whenever changing folders. I often keep the panel hidden, so this behavior is jarring. Can the extension be changed to change terminals but *not* hide/show the panel?

I am happy to make a PR.

**Comment by jscheffner** [comment]
Yes, that is kind of annoying. If you want to make a PR I'll be happy to merge it. The `Terminal.show` method, that is used to change the terminal has an argument for that.

**Comment by jscheffner** [comment]
My bad, that argument only prevents the focus of the terminal to change. If you make a PR it would still be nice to change that because that messes with split screens. Whenever you click into the tab that belongs to another workspace, it loses its focus.

**Comment by phatmann** [comment]
There is no way to change active terminals without showing the panel. The built-in "focus next terminal" command also shows the panel. I thought about a hack where we re-hide the panel if it was hidden, but as far as I can tell there is no way to check panel visibility (and it would probably look crappy). So unless you have another idea I will have to close this issue.

We could also submit a PR to vscode repo, but since there are no extension points around panel visibility, it could take a while.

**Comment by jscheffner** [comment]
Thanks a lot for the effort you put into this issue. I also had a look at it and didn't find a solution. I'll find out how contributing to VSCode works and how likely it is such a proposal would be accepted but it seems like a slow process.

**Comment by phatmann** [comment]
Perhaps they will consider making per-workspace terminals a feature and 100% solve this!

**Comment by jscheffner** [comment]
That would be even better but maybe also more time consuming to get through.

**Comment by phatmann** [comment]
All it takes is one maintainer who thinks its a cool and essential idea 😄

**Comment by jscheffner** [comment]
True, if I find the time I might follow [this process](https://github.com/microsoft/vscode/wiki/Extension-API-process) to get the API I want, I'm not sure how the process would look like to get per-workspace terminals.
