### ISSUE TITLE
Incorrect setting name in VS Code Description

### ISSUE THREAD

**Issue by grokpot** [jscheffner/vscode-workspace-terminals#30]
<img width="1697" alt="Screen Shot 2022-05-10 at 11 30 08" src="https://user-images.githubusercontent.com/1916031/167597306-424f8855-841e-477d-b9ea-a6ed8ec5f97a.png">

there is an unnecessary `s` in the setting name, which in my case, prevented the extension from functioning and caused some confusion.

Great extension btw 👍🏻

**Comment by jscheffner** [comment]
Hey, thanks for reporting and for the feedback. I will fix it in the docs but feel free to open a PR yourself if you want to.

**Comment by jscheffner** [comment]
I fixed the typo a while ago, but I haven't released the extension afterward. I will publish a new release soon. Thanks again for the feedback.
