### ISSUE TITLE
How do I configure what terminals to open?

### ISSUE THREAD

**Issue by DuchSuvaa** [jscheffner/vscode-workspace-terminals#41]
How do I configure what terminals to open? 

"Per default, Workspace Terminals will open a terminal per workspace folder if you are in a multi-root workspace."
I'm not sure if it has such function, but its description uses word "default" so, I suppose, it has some not-default behavior that can be configured, right?

**Comment by jscheffner** [comment]
Hey, there are some ways to configure the extension. They are described in the readme and you can find the settings in the extension settings. However, the sentence about the default behaviour is about when the extension is supposed to open the terminals, not which terminals it's supposed to open. If you're trying to configure for a specific workspace which terminals should open on startup this might not be the extension you're looking for. I think there are other extensions to do this,

**Comment by DuchSuvaa** [comment]
sorry, I got it wrong. thanks for answer

**Comment by jscheffner** [comment]
No problem
