### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by VanClement1** [jscheffner/vscode-workspace-terminals#48]
Is there any way to not have it populate duplicates? Sometimes VSCode will remember terminals that were open if it was the last workspace to be used. It would be nice if your extension could check to see if the terminal name already exists before it tries to open it again.

**Comment by jscheffner** [comment]
Hey, thanks for reporting, I didn't experience this myself yet. When I find the time I will work on a fix.

**Comment by jscheffner** [comment]
@VanClement1 Can you please share the steps to reproduce this? For me this isn't happening and the extension is already checking existing terminals before opening them.

**Comment by VanClement1** [comment]
It is just that sometimes when I open a window or workspace from the recent vscode list, it keeps the terminals that were open previously and populates them again

**Comment by aeb-dev** [comment]
We are having the same problem. Sometimes it just re-creates the terminals with the same names.

**Comment by jscheffner** [comment]
The extension is already checking if the terminal exists before it creates a new one. So if this sometimes doesn't work it's probably because vscode creates the terminals after the extension does.

Unfortunately it's a bit hard to debug because I can't reproduce it.

**Comment by aeb-dev** [comment]
It is probably something like that would it possible to delay the creation of terminals maybe? I might be a stupid idea I have no idea how extensions run

**Comment by jscheffner** [comment]
I am able to reproduce it now by running `> Developer: Reload Window`

Yes, delaying it might help but I'll also think about alternative solutions. It's also nice if the terminals are created fast.

**Comment by jscheffner** [comment]
I finally found some time to look into it and I think I fixed it. I changed the activation event of the extension and it should now only activate after the startup of vscode finished. This is anyway better for the performance of vscode.

I did not publish the fix yet, I want to try it out and see if the extension still behaves properly. I will publish it in the next days.

**Comment by jscheffner** [comment]
I just released the fix. Please check if it really fixed the issue for you, for me it did.
