### ISSUE TITLE
Disable behaviour for specific projects

### ISSUE THREAD

**Issue by lonix1** [jscheffner/vscode-workspace-terminals#49]
Assuming a multiroot workspace has many projects, a terminal is opened for each one. But some of them may not be wanted.

There is the manual trigger option,  but it's inconvenient. The default behaviour of opening terminals when the folder is opened is preferable.

Please consider adding a switch to disable this behaviour per project?

e.g. `.code-workspace`
```jsonc
"folders": [
  { "path": "/foo" },
  { "path": "/bar", autoOpenTerminal: false },          // do not create terminal for this project
  { "path": "/baz" },
  { "path": "/qux" }
]
```

**Comment by jscheffner** [comment]
Hey, as soon as you start configuring this per workspace, wouldn't it be easier to just directly configure the terminals you want to have? You wouldn't need this plugin at all.
